site_name: FIREFIT ROSE-AP
site_url: http://dih-squared.eu/TTE-FIREFIT
repo_url: https://github.com/Introsys/FIREFIT.ROSE-AP
site_description: FIREFIT ROSE-AP Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'index.md'
  - 'GCN - Generic Camera Node':
    - Introduction : 'gcn/index.md'
    - 'Getting Started' : 'gcn/getting-started.md'
    - 'User & Programmers Manual':
      - 'Architecture' : 'gcn/architecture.md'
      - 'User Guide': 'gcn/usermanual.md'
    - 'Installation & Administration Manual': 
      - 'Installation Guide': 'gcn/installationguide.md'
  - 'ICN - Image Classification Node':
    - Introduction : 'icn/index.md'
    - 'Getting Started' : 'icn/getting-started.md'
    - 'User & Programmers Manual':
      - 'Architecture' : 'icn/architecture.md'
      - 'User Guide': 'icn/usermanual.md'
    - 'Installation & Administration Manual': 
      - 'Installation Guide': 'icn/installationguide.md'